config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  get 'pages/residential'
  get 'pages/commercial'
  get 'pages/404'
  get 'quotes/quotes'
  get 'pages/charts'
  get 'pages/diagram'
  devise_for :users
  
  root to: "home#index"
  
  get '/commercial'   => 'pages#commercial'
  get "/home"         => 'home#index'
  get '/404'          => 'pages#404'
  get '/quotes'       => 'quotes#quotes'
  get '/residential'  => 'pages#residential'
  get '/charts'       => 'pages#charts'
  get '/diagram'      => 'pages#diagram'
  get '/news'         => 'home#news'
  get '/clients'      => 'home#clients'
  get '/contact'      => 'contact#index'
  get '/portfolio'    => 'home#portfolio'
  get '/charts'       => 'charts#dashboard'
  #get '/maps'       => 'maps#dashboard'
  post '/leads'       => 'leads#create'
  post '/quotes'      => 'quotes#create'
 
  get 'buildinglocalisation' => 'buildinglocalisation#building'
  get '/speak'       => 'speak#speech'
  # get '/speak', to: 'speak#text_to_speech', as: 'button'

  get 'get_building_by_customer/:customer_id', to: 'interventions#get_building_by_customer'
  get '/create_interv' => 'interventions#new'

  get 'get_battery_by_building/:building_id', to: 'interventions#get_battery_by_building'
  
  get 'get_column_by_battery/:battery_id', to: 'interventions#get_column_by_battery'

  get 'get_elevator_by_column/:column_id', to: 'interventions#get_elevator_by_column'


  devise_scope :user do 
    get "/signup"     => "devise/registrations#new" 
    get "/signin"     => "devise/sessions#new" 
    get "/signout"    => "devise/sessions#destroy"
    get "/changepassword" => "devise/passwords#new"
    get '/interventions' => 'interventions#index'

    post "/signup"     => "devise/registrations#new" 
    post "/signin"     => "devise/sessions#new" 
    post "/signout"    => "devise/sessions#destroy"
    post "/changepassword" => "devise/passwords#new"
  end
  resources :interventions do
      # collection do
      get :get_building_by_customer
      get :building_search
      get :get_battery_by_building
      get :battery_search
      # end
  end

  resources :quotes, only: [:new, :create]
  
end

app/models/intervention.rb
class Intervention < ApplicationRecord
    belongs_to :employee, optional: true
    belongs_to :customer, optional: true
    belongs_to :building, optional: true
    belongs_to :battery, optional: true
    belongs_to :column, optional: true
    belongs_to :elevator, optional: true

    validates :author_id, presence:true
end

app/controllers/interventions_controller.rb
require 'zendesk_api'
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]
  # before_action :require_user, :only => 'show'
  before_action :is_employee #check if current user is employee

  # GET /interventions or /interventions.json
  
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1 or /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    @intervention = Intervention.new
  end

  # GET /interventions/1/edit
  def edit
  end

  #Get the building for the selected customer
  def get_building_by_customer
    puts "get building by customer"
    @building = Building.where(customer_id: params[:customer_id])
        respond_to do |format|
        format.json { render :json => @building }
    end
  end
  
  #Get the battery for the selected building
  def get_battery_by_building
    puts "get battery by building"
    @battery = Battery.where(building_id: params[:building_id])
        respond_to do |format|
        format.json { render :json => @battery }
    end
  end

  #Get the column for the selected battery
  def get_column_by_battery
    puts "get column by battery"
    @column = Column.where(battery_id: params[:battery_id])
    puts @column
        respond_to do |format|
        format.json { render :json => @column }
    end
  end
  #Get the elevator for the selected column
  def get_elevator_by_column
    puts "get elevator by column"
    @elevator = Elevator.where(column_id: params[:column_id])
        respond_to do |format|
        format.json { render :json => @elevator }
    end
  end

  def create_zendesk
 
    # @employee_name = Employee.find_by(current_user.id)
    # @customer_name = Customer.find_by(customer_id)
    # @field_employee = Employee.find_by(employee_id)

    client = ZendeskAPI::Client.new do |config|
        config.url = ENV['ZENDESK_URL']
        config.username = ENV["ZENDESK_EMAIL"]
        config.token = ENV["ZENDESK_TOKEN"]
    end
    ZendeskAPI::Ticket.create!(client,
    :subject => "Intervention from Employee ##{@intervention.author_id}",
    :comment => {
        :value => "Needs Intervention in the building ##{@intervention.building_id} for the customer: #{@intervention.customer_id}.
        
        Battery ID : #{@batt}
        Column ID : #{@col} 
        Elevator ID : #{@elev}

        The employee assign is : #{@intervention.employee_id}.
        
        Brief description of the intervention: #{@intervention.report}."
    },

    :priority => "urgent",
    :type => "problem"
    )
  end

  # POST /interventions or /interventions.json
  def create
    @intervention = Intervention.new
    
    @batt = params[:Battery]
    @col = params[:Column]
    @elev = params[:Elevator]
    @intervention.author_id = current_user.id
    @intervention.customer_id = params[:Customer]
    @intervention.building_id = params[:Building]
    @intervention.battery_id = params[:Battery]
    @intervention.column_id = params[:Column]
    @intervention.elevator_id = params[:Elevator]
    @intervention.employee_id = params[:Employee]
    @intervention.report = params[:report]
    
    if @intervention.elevator_id 
        @intervention.battery_id = nil
        @intervention.column_id = nil
    elsif @intervention.column_id
        @intervention.battery_id = nil
    end    


    @intervention.save!
 

    if @intervention.save
      create_zendesk()

      redirect_to interventions_path, notice: "Message sent!"
    # else    
    #   redirect_to "/leads", notice: "Invalid fields!"
    end
  end


  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to @intervention, notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
        params.permit(:author_id, :customer_id, :building_id, :battery_id, :column_id, :elevator_id, :employee_id, :intervention_start, :intervention_end, :result, :report, :status)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<div class="row no-gutters wow slideInUp" data-wow-duration="1s">
  <div class="container home-form col-md-4">

    <%= form_with(model: intervention, local: true) do |form| %>

      <% if intervention.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>
          <ul>
            <% intervention.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="field">
        <%= form.label :customer_id %>
          <%= select_tag "Customer", options_from_collection_for_select(Customer.all, "id", "company_name"), prompt: "Customer Company Name", class: "custom-select", required: true %>
      </div>

      <br/>

      <div class="field building">
        <%= form.label :building_id %>
          <%= select_tag "Building", options_from_collection_for_select(Building.all, "id", "id"), prompt: "Building ID", class: "custom-select", required: true %>
      </div>

      <br/>

      <div class="field battery">
        <%= form.label :battery_id %>
          <%= select_tag "Battery", options_from_collection_for_select(Battery.all, "id", "id"), prompt: "Battery ID", class: "custom-select" %>
      </div>

      <br/>
      <div class="field column">
        <%= form.label :column_id %>
          <%= select_tag "Column", options_from_collection_for_select(Column.all, "id", "id"), prompt: "Column ID", class: "custom-select" %>
      </div>

      <br/>

      <div class="field elevator">
        <%= form.label :elevator_id %>
          <%= select_tag "Elevator", options_from_collection_for_select(Elevator.all, "id", "id"), prompt: "Elevator ID", class: "custom-select" %>
      </div>

      <br/>

      <div class="field">
        <%= form.label :employee_id %>
          <%= select_tag "Employee", options_from_collection_for_select(Employee.all, "id", "fullname"), prompt: "Employee Name", class: "custom-select" %>
      </div>

      <br/>

      <div class="field">
        <%= form.label :report %>
          <%= text_area :report, "Description", size: "50x3" %>
      </div>

      <br/>

      <div class="actions">
        <%= form.submit "Send Intervention" , class: 'btn btn-primary'  %>
      </div>
    <% end %>
  </div>
</div>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<section class="pb-0" id="interventions">
<div class="container-fluid text-center pl-80 pr-80">
<p id="notice"><%= notice %></p>
    <div class="col-md-12 pt-30">
      <h1>Interventions</h1>
    </div>
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Author</th>
            <th scope="col">Customer</th>
            <th scope="col">Building</th>
            <th scope="col">Battery</th>
            <th scope="col">Column</th>
            <th scope="col">Elevator</th>
            <th scope="col">Employee</th>
            <th scope="col-2">Intervention start</th>
            <th scope="col-2">Intervention end</th>
            <th scope="col">Result</th>
            <th scope="col">Report</th>
            <th scope="col">Status</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @interventions.each do |intervention| %>
            <tr scope="row">  
              <td><%= intervention.author_id %></td>
              <td><%= intervention.customer_id %></td>
              <td><%= intervention.building_id %></td>
              <td><%= intervention.battery_id %></td>
              <td><%= intervention.column_id %></td>
              <td><%= intervention.elevator_id %></td>
              <td><%= intervention.employee_id %></td>
              <td><%= intervention.intervention_start %></td>
              <td><%= intervention.intervention_end %></td>
              <td><%= intervention.result %></td>
              <td><%= intervention.report %></td>
              <td><%= intervention.status %></td>
              <td><%= link_to 'Show', intervention %></td>
              <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
              <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div> 
  <br>
<div class="container-fluid pt-50 pb-80">
  <div class="row text-center">
      <div class="col">
          <%= link_to 'New Intervention', new_intervention_path %>
      </div>
  </div>
</div>

app/views/interventions/new.html.erb
<div class="container text-center" id="interventions">
    <div class="row">
        <div class="col pt-30">
            <h1>New Intervention</h1>
        </div>
    </div>
    <%= render 'form', intervention: @intervention %>

    <div class="row text-center">
        <div class="col">
            <%= link_to 'Back to Interventions', interventions_path %>
        </div>
    </div>
</div>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @intervention.author_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @intervention.employee_id %>
</p>

<p>
  <strong>Building:</strong>
  <%= @intervention.building_id %>
</p>

<p>
  <strong>Battery:</strong>
  <%= @intervention.battery_id %>
</p>

<p>
  <strong>Column:</strong>
  <%= @intervention.column_id %>
</p>

<p>
  <strong>Elevator:</strong>
  <%= @intervention.elevator_id %>
</p>

<p>
  <strong>Intervention start:</strong>
  <%= @intervention.intervention_start %>
</p>

<p>
  <strong>Intervention end:</strong>
  <%= @intervention.intervention_end %>
</p>

<p>
  <strong>Result:</strong>
  <%= @intervention.result %>
</p>

<p>
  <strong>Report:</strong>
  <%= @intervention.report %>
</p>

<p>
  <strong>Status:</strong>
  <%= @intervention.status %>
</p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>